#!/bin/bash

EXE=${0%/*}/generate-notices.sh

# Hold Ready for Pickup
$EXE --granularity messagebee-hold-ready-sms --send-xml --window "1 hours" --end-date "$(date +'%FT%H:%M:%S')"

# Curbside Offer SMS Notification
$EXE --granularity messagebee-curbside-offer-sms --send-xml --window "1 hours" --end-date "$(date +'%FT%H:%M:%S')"

# Curbside Confirmation SMS Notification
$EXE --granularity messagebee-curbside-confirm-sms --send-xml --window "1 hours" --end-date "$(date +'%FT%H:%M:%S')"
